// ??????
import { GradeInfo } from './QuestionTypes';

export const GRADES: GradeInfo[] = [
  { id: 'primary1', name: '???', stage: 'primary' },
  { id: 'primary2', name: '???', stage: 'primary' },
  { id: 'primary3', name: '???', stage: 'primary' },
  { id: 'primary4', name: '???', stage: 'primary' },
  { id: 'primary5', name: '???', stage: 'primary' },
  { id: 'primary6', name: '???', stage: 'primary' },
  { id: 'junior1', name: '???', stage: 'junior' },
  { id: 'junior2', name: '???', stage: 'junior' },
  { id: 'junior3', name: '???', stage: 'junior' }
];
